<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Agenda.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Agenda.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-10 08:06:33 */
/* http://harviacode.com */

 class Agenda extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Agenda_model','model');
      if ($this->cl->acl("agenda")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('id_agenda', 'id_agenda', 'trim');
		$this->form_validation->set_rules('agenda', 'agenda', 'trim|xss_clean|required');
    $this->form_validation->set_rules('date', 'Waktu', 'trim|xss_clean|required');
		$this->form_validation->set_rules('desc', 'Perihal', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Agenda');
    $this->layouts->view(config_item("cpanel").'content/agenda/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Agenda');
        $data=array('layout_title' => 'Agenda',
										'id_agenda' => $row->id_agenda,
										'agenda' => $row->agenda,
										'desc' => $row->desc,
										'date' => $row->date,
										'slug' => $row->slug,
										'created_by' => $row->created_by,
										'created_at' => $row->created_at,
										'update_by' => $row->update_by,
										'update_at' => $row->update_at,
									);
				 $this->layouts->view(config_item("cpanel").'content/agenda/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/agenda/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'agenda' => $this->input->post('agenda',TRUE),
																'desc' => $this->input->post('desc',TRUE),
                                'date' => $this->input->post('date',TRUE),
																'slug' => slug($this->input->post('agenda',TRUE)),
                                'created_by' => sess('id_auth'),
																'created_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Agenda');
      $data = array('layout_title' => 'Agenda',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'agenda/tambah/aksi'),
											'id_agenda' => set_value('id_agenda'),
                      'date' => set_value('date'),
											'agenda' => set_value('agenda'),
                      'desc'  =>set_value('desc'),
											);
			 $this->layouts->view(config_item("cpanel").'content/agenda/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/agenda/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'agenda' => $this->input->post('agenda',TRUE),
																'slug' => slug($this->input->post('agenda',TRUE)),
                                'date' => $this->input->post('date',TRUE),
                                'desc' => $this->input->post('desc',TRUE),
                                'update_by' => sess('id_auth'),
																'update_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Agenda');
        $data = array('layout_title' => 'Agenda',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'agenda/edit/'.$id.'/aksi'),
											'id_agenda' => set_value('id_agenda', $row->id_agenda),
											'agenda' => set_value('agenda', $row->agenda),
                      'date' => set_value('date',$row->date),
											'desc' => set_value('desc', $row->desc),
											);
			 $this->layouts->view(config_item("cpanel").'content/agenda/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/agenda/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
