<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Album.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Album.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-21 21:54:35 */
/* http://harviacode.com */

 class Album extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Album_model','model');
      if ($this->cl->acl("album")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('id_album', 'id_album', 'trim');
		$this->form_validation->set_rules('album', 'album', 'trim|xss_clean|required');
		$this->form_validation->set_rules('desc', 'desc', 'trim|xss_clean');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Album');
    $data['row'] = $this->model->get_data()->result();
    $this->layouts->view(config_item("cpanel").'content/album/index',array(),$data);
  }

 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Album');
        $data=array('layout_title' => 'Album',
										'id_album' => $row->id_album,
										'album' => $row->album,
										'desc' => $row->desc,
									);
				 $this->layouts->view(config_item("cpanel").'content/album/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/album/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'album' => $this->input->post('album',TRUE),
																'desc' => $this->input->post('desc',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Album');
      $data = array('layout_title' => 'Album',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'album/tambah/aksi'),
											'id_album' => set_value('id_album'),
											'album' => set_value('album'),
											'desc' => set_value('desc'),
											);
			// $this->layouts->view(config_item("cpanel").'content/album/form',array(),$data);
  //MODAL TAMBAH
  $this->layouts->view(config_item("cpanel").'content/album/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'album' => $this->input->post('album',TRUE),
																'desc' => $this->input->post('desc',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Album');
        $data = array('layout_title' => 'Album',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'album/edit/'.$id.'/aksi'),
											'id_album' => set_value('id_album', $row->id_album),
											'album' => set_value('album', $row->album),
											'desc' => set_value('desc', $row->desc),
											);
			 //$this->layouts->view(config_item("cpanel").'content/album/form',array(),$data);
  //MODAL EDIT
  $this->layouts->view(config_item("cpanel").'content/album/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
       // $this->model->get_delete_image(array("id_album"=>$id),"galery_image");
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

function upload($id)
  {
    $row = $this->model->get_where($id);
    $data = array('id_album' =>$row->id_album ,'album'=>$row->album );
    $this->load->view(config_item("cpanel").'content/album/upload',$data);
  }

  function get_image_upload($id){
      if ($this->input->is_ajax_request()) {
        $file_name = substr(sha1(date('Y-m-d h:i:s')), 0, 6);
        $config['upload_path']   = './temp/upload/img';
        $config['allowed_types'] = 'jpg|png';
        $config['file_name']     = $file_name;
        $this->load->library('upload',$config);




        if($this->upload->do_upload('userfile')){
          $token=$this->input->post('token_foto');
          $nama=$this->upload->data('file_name');
          $data = array(
                        'image'=>$nama,
                        'token'=>$token,
                        'id_album'  => $id
                      );
          $this->model->get_insert_image('galery_image',$data);


          //Image Resizing
          $config1['image_library'] = 'gd2';
          $config1['source_image'] =  $this->upload->upload_path.$this->upload->file_name;
          $config1['new_image'] =  "./temp/upload/thumbs/".$this->upload->file_name;
          $config1['create_thumb'] = FALSE;
          $config1['maintain_ratio'] = FALSE;
          $config1['height'] = 330;
          $config1['width']  = 440;

          $this->load->library('image_lib', $config1);

          $this->image_lib->resize();
        }
      }

}


function get_view_galery_json($id)
	{


		$myitemfiles=$this->model->get_where_image(array('id_album'=>$id),'galery_image');

		foreach($myitemfiles->result_array() as $file)
		{ //get an array which has the names of all the files and loop through it
        $obj['name'] = $file['image']; //get the filename in array
        $obj['size'] = filesize("./temp/upload/img/".$file['image']); //get the flesize in array
				$obj['token']=$file['token'];
        $result[] = $obj; // copy it to another array

      }
        header('Content-Type: application/json');
        echo json_encode($result); // now you have a json response which you can use in client side
	}



  function get_galery_remove(){

  		//Ambil token foto
  		$token=$this->input->post('token');

  		$this->model->get_delete_image(array('token'=>$token),'galery_image');



  		echo "{}";
  	}


    function json_image($id) {
        header('Content-Type: application/json');
        echo $this->model->json_image($id);
    }

    function hapus_image($id){
     if ($this->input->is_ajax_request()) {
         $this->model->get_delete_image(array("id_galery_image"=>$id),"galery_image");
         $data['alert'] = 'Berhasil menghapus!';
         echo json_encode($data);
       }
   }




}
/* End Controller */
