<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Banner.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Banner.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-20 20:03:54 */
/* http://harviacode.com */

 class Banner extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Banner_model','model');
      if ($this->cl->acl("banner")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('image', 'image', 'trim|xss_clean|required');
		$this->form_validation->set_rules('desc', 'desc', 'trim|xss_clean');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Banner');
    $data['row'] = $this->model->get_data()->result();
    $this->layouts->view(config_item("cpanel").'content/banner/index',array(),$data);
  }

 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Banner');
        $data=array('layout_title' => 'Banner',
										'id_banner' => $row->id_banner,
										'image' => $row->image,
										'desc' => $row->desc,
									);
				  $this->layouts->view(config_item("cpanel").'content/banner/detail',array(),$data);
//MODAL DETAIL
// $this->layouts->view(config_item("cpanel").'content/banner/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'image' => $this->input->post('image',TRUE),
																'desc' => $this->input->post('desc',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Banner');
      $data = array('layout_title' => 'Banner',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'banner/tambah/aksi'),
											'id_banner' => set_value('id_banner'),
											'image' => set_value('image'),
											'desc' => set_value('desc'),
											);
			 // $this->layouts->view(config_item("cpanel").'content/banner/form',array(),$data);
  //MODAL TAMBAH
  $this->layouts->view(config_item("cpanel").'content/banner/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'image' => $this->input->post('image',TRUE),
																'desc' => $this->input->post('desc',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Banner');
        $data = array('layout_title' => 'Banner',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'banner/edit/'.$id.'/aksi'),
											'id_banner' => set_value('id_banner', $row->id_banner),
											'image' => set_value('image', $row->image),
											'desc' => set_value('desc', $row->desc),
											);
			 // $this->layouts->view(config_item("cpanel").'content/banner/form',array(),$data);
  //MODAL EDIT
  $this->layouts->view(config_item("cpanel").'content/banner/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
