<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Berita.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Berita.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-07 16:49:22 */
/* http://harviacode.com */

 class Berita extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Berita_model','model');
      if ($this->cl->acl("berita")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('judul', 'judul', 'trim|xss_clean|required');
    $this->form_validation->set_rules('desc', 'Konten', 'trim|xss_clean|required');
    $this->form_validation->set_rules('seotitle', 'Title Seo', 'trim|xss_clean|required');
		$this->form_validation->set_rules('image', 'Gambar', 'trim|xss_clean');
    $this->form_validation->set_rules('kategori', 'Kategori', 'trim|xss_clean|required');
    $this->form_validation->set_rules('komentar', 'Komentar', 'trim|xss_clean|required|numeric');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Berita');
    $this->layouts->view(config_item("cpanel").'content/berita/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where_join($id)){
      $this->layouts->set_title('Berita');
        $data=array('layout_title' => 'Berita',
										'id_berita' => $row->id_berita,
										'judul' => $row->judul,
										'desc' => $row->desc,
										'image' => $row->image,
										'slug' => $row->slug,
										'hits' => $row->hits,
                    'komentar' => $row->komentar,
                    'kategori' => $row->kategori,
										'created_at' => $row->created_at,
									);
				 $this->layouts->view(config_item("cpanel").'content/berita/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/berita/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'judul' => $this->input->post('judul',TRUE),
																'desc' => $this->input->post('desc',TRUE),
																'image' => $this->input->post('image',TRUE),
																'slug' => slug($this->input->post('seotitle',TRUE)),
                                'komentar' => $this->input->post('komentar',TRUE),
                                'id_kategori' => $this->input->post('kategori',TRUE),
																'created_by' => sess('id_auth'),
																'created_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Berita');
      $data = array('layout_title' => 'Berita',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'berita/tambah/aksi'),
											'id_berita' => set_value('id_berita'),
											'judul' => set_value('judul'),
											'desc' => set_value('desc'),
											'image' => set_value('image'),
                      'slug'  => set_value('slug'),
                      'komentar'=>set_value('komentar'),
											'kategori' => set_value('kategori'),
											);
			 $this->layouts->view(config_item("cpanel").'content/berita/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/berita/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'judul' => $this->input->post('judul',TRUE),
																'desc' => $this->input->post('desc',TRUE),
																'image' => $this->input->post('image',TRUE),
																'slug' => slug($this->input->post('seotitle',TRUE)),
                                'id_kategori' => $this->input->post('kategori',TRUE),
                                'komentar' => $this->input->post('komentar',TRUE),
																'update_by' => sess('id_auth'),
																'update_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Berita');
        $data = array('layout_title' => 'Berita',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'berita/edit/'.$id.'/aksi'),
											'id_berita' => set_value('id_berita', $row->id_berita),
											'judul' => set_value('judul', $row->judul),
											'desc' => set_value('desc', $row->desc),
											'image' => set_value('image', $row->image),
                      'slug'  => set_value('slug', $row->slug),
                      'komentar'=>set_value('komentar',$row->komentar),
                      'kategori' => set_value('kategori', $row->id_kategori),
											);
			 $this->layouts->view(config_item("cpanel").'content/berita/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/berita/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
