<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Kategori.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-09 17:29:45 */
/* http://harviacode.com */

 class Kategori extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Kategori_model','model');
      if ($this->cl->acl("kategori")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('kategori', 'kategori', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Kategori');
    $this->layouts->view(config_item("cpanel").'content/kategori/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


//  function detail($id){
//     if($row=$this->model->get_where($id)){
//       $this->layouts->set_title('Kategori');
//         $data=array('layout_title' => 'Kategori',
// 										'id_kategori' => $row->id_kategori,
// 										'kategori' => $row->kategori,
// 									);
// 				 //$this->layouts->view(config_item("cpanel").'content/kategori/detail',array(),$data);
// //MODAL DETAIL
//           $this->layouts->view(config_item("cpanel").'content/kategori/detail',array(),$data,false);
//     }else {
//         $this->error_404();
//     }
//   }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'kategori' => $this->input->post('kategori',TRUE),
                                'slug'     =>slug($this->input->post('kategori',TRUE)),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Kategori');
      $data = array('layout_title' => 'Kategori',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'kategori/tambah/aksi'),
											'id_kategori' => set_value('id_kategori'),
											'kategori' => set_value('kategori'),
											);
			 //$this->layouts->view(config_item("cpanel").'content/kategori/form',array(),$data);
  //MODAL TAMBAH
        $this->layouts->view(config_item("cpanel").'content/kategori/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'kategori' => $this->input->post('kategori',TRUE),
                                'slug'     =>slug($this->input->post('kategori',TRUE)),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Kategori');
        $data = array('layout_title' => 'Kategori',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'kategori/edit/'.$id.'/aksi'),
											'id_kategori' => set_value('id_kategori', $row->id_kategori),
											'kategori' => set_value('kategori', $row->kategori),
											);
			 //$this->layouts->view(config_item("cpanel").'content/kategori/form',array(),$data);
  //MODAL EDIT
    $this->layouts->view(config_item("cpanel").'content/kategori/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
