<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Linkterkait.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Linkterkait.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-20 19:10:41 */
/* http://harviacode.com */

 class Linkterkait extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Linkterkait_model','model');
      if ($this->cl->acl("linkterkait")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('nama', 'nama', 'trim|xss_clean|required');
		$this->form_validation->set_rules('url', 'url', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Link Terkait');
    $data['row'] = $this->model->get_data()->result();
    $this->layouts->view(config_item("cpanel").'content/linkterkait/index',array(),$data);
  }

//  function detail($id){
//     if($row=$this->model->get_where($id)){
//       $this->layouts->set_title('Link Terkait');
//         $data=array('layout_title' => 'Link Terkait',
// 										'id_link' => $row->id_link,
// 										'nama' => $row->nama,
// 										'url' => $row->url,
// 									);
// 				 $this->layouts->view(config_item("cpanel").'content/linkterkait/detail',array(),$data);
// //MODAL DETAIL
// //$this->layouts->view(config_item("cpanel").'content/linkterkait/detail',arra`y(),$data,false);
//     }else {
//         $this->error_404();
//     }
//   }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'nama' => $this->input->post('nama',TRUE),
																'url' => $this->input->post('url',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Link Terkait');
      $data = array('layout_title' => 'Link Terkait',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'linkterkait/tambah/aksi'),
											'id_link' => set_value('id_link'),
											'nama' => set_value('nama'),
											'url' => set_value('url'),
											);
			 // $this->layouts->view(config_item("cpanel").'content/linkterkait/form',array(),$data);
  //MODAL TAMBAH
  $this->layouts->view(config_item("cpanel").'content/linkterkait/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'nama' => $this->input->post('nama',TRUE),
																'url' => $this->input->post('url',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Link Terkait');
        $data = array('layout_title' => 'Link Terkait',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'linkterkait/edit/'.$id.'/aksi'),
											'id_link' => set_value('id_link', $row->id_link),
											'nama' => set_value('nama', $row->nama),
											'url' => set_value('url', $row->url),
											);
			 // $this->layouts->view(config_item("cpanel").'content/linkterkait/form',array(),$data);
  //MODAL EDIT
  $this->layouts->view(config_item("cpanel").'content/linkterkait/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
