<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Litbang.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Litbang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-30 18:31:26 */
/* http://harviacode.com */

 class Litbang extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Litbang_model','model');
      $this->load->library("Cl");
      if ($this->cl->acl("litbang")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('judul', 'judul', 'trim|xss_clean|required');
		$this->form_validation->set_rules('penyusun', 'penyusun', 'trim|xss_clean|required');
		$this->form_validation->set_rules('deskripsi', 'deskripsi', 'trim|xss_clean');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Litbang');
    $this->layouts->view('administrator/content/litbang/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Litbang');
        $data=array('layout_title' => 'Litbang',
										'id_litbang' => $row->id_litbang,
										'slug' => $row->slug,
										'judul' => $row->judul,
										'penyusun' => $row->penyusun,
										'deskripsi' => $row->deskripsi,
										'file' => $row->file,
										'created_at' => $row->created_at,
									);
				 $this->layouts->view('administrator/content/litbang/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view('administrator/content/litbang/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
          if(isset($_FILES['userfile']['name']) && $_FILES['userfile']['name']!=""){
              $file_name = substr($_FILES['userfile']['name'],-4);
              $file = $this->input->post('userfile',true)."".$file_name;
            }else {
              $file = null;
            }
            $this->form_validation->set_rules('userfile', 'File', 'trim|xss_clean|callback__cekfile['.$file.']');
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'judul' => $this->input->post('judul',TRUE),
                                'slug' => strtolower(url_title($this->input->post('judul',TRUE),'dash')),
																'penyusun' => $this->input->post('penyusun',TRUE),
																'deskripsi' => $this->input->post('deskripsi',TRUE),
																'file' => $file,
																'created_at' => date('Ymd'),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Litbang');
      $data = array('layout_title' => 'Litbang',
                      'button'=>'tambah',
                      'aksi' =>site_url('administrator/litbang/tambah/aksi'),
											'id_litbang' => set_value('id_litbang'),
											'slug' => set_value('slug'),
											'judul' => set_value('judul'),
											'penyusun' => set_value('penyusun'),
											'deskripsi' => set_value('deskripsi'),
											'userfile' => set_value('userfile',"litbang-".date('dmYhis')),
											);
			 $this->layouts->view('administrator/content/litbang/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view('administrator/content/litbang/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
            if(isset($_FILES['userfile']['name']) && $_FILES['userfile']['name']!=""){
                if ($this->input->post('userfile',true)=="") {
                  $file_name = substr($_FILES['userfile']['name'],-4);
                  $file= "litbang-".date('dmYhis')."".$file_name;
                }else {
                  $file = $this->input->post('userfile',true);
                }
              }else {
                $file = $this->input->post('userfile',true);
              }
                $this->form_validation->set_rules('userfile', 'foto', 'trim|xss_clean|callback__cekfileedit['.$file.']');
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
                                'judul' => $this->input->post('judul',TRUE),
																'slug' => strtolower(url_title($this->input->post('judul',TRUE),'dash')),
																'penyusun' => $this->input->post('penyusun',TRUE),
																'deskripsi' => $this->input->post('deskripsi',TRUE),
																'file' => $file,
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Litbang');
        $data = array('layout_title' => 'Litbang',
                      'button'=>'edit',
                      'aksi' =>site_url('administrator/litbang/edit/'.$id.'/aksi'),
											'id_litbang' => set_value('id_litbang', $row->id_litbang),
											'judul' => set_value('judul', $row->judul),
											'penyusun' => set_value('penyusun', $row->penyusun),
											'deskripsi' => set_value('deskripsi', $row->deskripsi),
											'userfile' => set_value('userfile', $row->file),
											);
			 $this->layouts->view('administrator/content/litbang/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view('administrator/content/litbang/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
