<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Pengguna.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Pengguna.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-02 12:17:41 */
/* http://harviacode.com */

 class Pengguna extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Pengguna_model','model');
      if ($this->cl->acl("pengguna")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('name', 'name', 'trim|xss_clean|required');
		$this->form_validation->set_rules('telepon', 'telepon', 'trim|xss_clean|numeric');
		$this->form_validation->set_rules('email', 'email', 'trim|xss_clean|required|valid_email');
		$this->form_validation->set_rules('groups', 'groups', 'trim|xss_clean|required|numeric');
    $this->form_validation->set_rules('image', 'Gambar', 'trim|xss_clean');
		$this->form_validation->set_rules('active', 'active', 'trim|xss_clean|required|numeric');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Pengguna');
    $data['row'] = $this->model->get_join()->result();
    $this->layouts->view(config_item("cpanel").'content/pengguna/index',array(),$data);
  }

 function detail($id){
    if($row=$this->model->get_where_join($id)){
      $this->layouts->set_title('Pengguna');
        $data=array('layout_title' => 'Pengguna',
										'id_auth' => $row->id_auth,
										'name' => $row->name,
										'telepon' => $row->telepon,
										'email' => $row->email,
										'password' => $row->password,
                    'image' => $row->image,
										'groups' => $row->level,
										'active' => $row->active,
										'created_by' => $row->created_by,
										'update_by' => $row->update_by,
										'created_at' => $row->created_at,
										'update_at' => $row->update_at,
									);
				 $this->layouts->view(config_item("cpanel").'content/pengguna/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/pengguna/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
          $this->form_validation->set_rules("pwd","Password baru ","trim|required|min_length[5]|max_length[50]");
          $this->form_validation->set_rules("pwd_con","Konfirmasi Password baru","trim|required|matches[pwd]|xss_clean");
            $this->_rules();

            if ($this->form_validation->run()) {
                $insert = array(
																'name' => $this->input->post('name',TRUE),
																'telepon' => $this->input->post('telepon',TRUE),
																'email' => $this->input->post('email',TRUE),
																'password' => pass_enc($this->input->post('password')),
																'groups' => $this->input->post('groups',TRUE),
                                'image' => $this->input->post('image',TRUE),
																'active' => $this->input->post('active',TRUE),
                                'created_by' => $this->session->userdata("id_auth"),
																'created_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Pengguna');
      $data = array('layout_title' => 'Pengguna',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'pengguna/tambah/aksi'),
											'id_auth' => set_value('id_auth'),
											'name' => set_value('name'),
											'telepon' => set_value('telepon'),
											'email' => set_value('email'),
											'password' => set_value('password'),
											'groups' => set_value('groups'),
											'active' => set_value('active'),
                      'image' => set_value('image'),
											);
			 $this->layouts->view(config_item("cpanel").'content/pengguna/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/pengguna/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'name' => $this->input->post('name',TRUE),
																'telepon' => $this->input->post('telepon',TRUE),
																'email' => $this->input->post('email',TRUE),
																'password' => $this->input->post('password',TRUE),
																'groups' => $this->input->post('groups',TRUE),
																'active' => $this->input->post('active',TRUE),
                                'image' => $this->input->post('image',TRUE),
                                'update_by' => $this->session->userdata("id_auth"),
                                'update_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Pengguna');
        $data = array('layout_title' => 'Pengguna',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'pengguna/edit/'.$id.'/aksi'),
											'id_auth' => set_value('id_auth', $row->id_auth),
											'name' => set_value('name', $row->name),
											'telepon' => set_value('telepon', $row->telepon),
											'email' => set_value('email', $row->email),
											'password' => set_value('password', $row->password),
                      'image' => set_value('image',$row->image),
											'groups' => set_value('groups', $row->groups),
											'active' => set_value('active', $row->active),
											);
			 $this->layouts->view(config_item("cpanel").'content/pengguna/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/pengguna/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }

}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

function change_password($id){
  $data['id_auth'] = $id;
  $this->layouts->view(config_item("cpanel").'content/pengguna/change',array(),$data,false);
}

function aksi_pwd($id)
{
  if ($this->input->is_ajax_request()) {
    $json = array('success' =>false , "alert"=>array());
    $this->form_validation->set_rules("pwd","Password baru ","trim|required|min_length[5]|max_length[50]");
    $this->form_validation->set_rules("pwd_con","Konfirmasi Password baru","trim|required|matches[pwd]|xss_clean");
    $this->form_validation->set_error_delimiters('<p class="text-danger">','</p>');
    if($this->form_validation->run())
      {
      $password = pass_enc($this->input->post('pwd_con'));
      $this->model->get_update($id,array("password"=>$password));
      $json['alert']  = "Berhasil mengubah password!";
      $json['success'] = true;
      }else {
        foreach ($_POST as $key => $value) {
          $json['alert'][$key] = form_error($key);
         }
      }
    echo json_encode($json);
  }
}



}
/* End Controller */
