<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Profile.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Profile.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-20 22:35:55 */
/* http://harviacode.com */

 class Profile extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Profile_model','model');
      if ($this->cl->acl("profile")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('title', 'title', 'trim|xss_clean|required');
		$this->form_validation->set_rules('alamat', 'alamat', 'trim|xss_clean|required');
		$this->form_validation->set_rules('tlp', 'tlp', 'trim|xss_clean|required');
		$this->form_validation->set_rules('fax', 'fax', 'trim|xss_clean|required');
		$this->form_validation->set_rules('web', 'web', 'trim|xss_clean|required');
		$this->form_validation->set_rules('email', 'email', 'trim|xss_clean|required');
    $this->form_validation->set_rules('facebook', 'facebook', 'trim|xss_clean|required');
    $this->form_validation->set_rules('twitter', 'twitter', 'trim|xss_clean|required');
    $this->form_validation->set_rules('instagram', 'instagram', 'trim|xss_clean|required');
    $this->form_validation->set_rules('youtube', 'youtube', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }


 function index(){
    if($row=$this->model->get_where(1)){
      $this->layouts->set_title('Profile');
        $data=array('layout_title' => 'Profile',
										'id_profile' => $row->id_profile,
										'title' => $row->title,
										'alamat' => $row->alamat,
										'tlp' => $row->tlp,
										'fax' => $row->fax,
										'web' => $row->web,
										'email' => $row->email,
                    'facebook' => $row->facebook,
                    'twitter' => $row->twitter,
                    'instagram' => $row->instagram,
                    'youtube' => $row->youtube,

									);
				 $this->layouts->view(config_item("cpanel").'content/profile/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/profile/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }



 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'title' => $this->input->post('title',TRUE),
																'alamat' => $this->input->post('alamat',TRUE),
																'tlp' => $this->input->post('tlp',TRUE),
																'fax' => $this->input->post('fax',TRUE),
																'web' => $this->input->post('web',TRUE),
																'email' => $this->input->post('email',TRUE),
                                'facebook' => $this->input->post('facebook',TRUE),
                                'twitter' => $this->input->post('twitter',TRUE),
                                'instagram' => $this->input->post('instagram',TRUE),
                                'youtube' => $this->input->post('youtube',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where(1)){
        $this->layouts->set_title('Profile');
        $data = array('layout_title' => 'Profile',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'profile/edit/1/aksi'),
											'id_profile' => set_value('id_profile', $row->id_profile),
											'title' => set_value('title', $row->title),
											'alamat' => set_value('alamat', $row->alamat),
											'tlp' => set_value('tlp', $row->tlp),
											'fax' => set_value('fax', $row->fax),
											'web' => set_value('web', $row->web),
											'email' => set_value('email', $row->email),
                      'facebook' => $row->facebook,
                      'twitter' => $row->twitter,
                      'instagram' => $row->instagram,
                      'youtube' => $row->youtube,
											);
			 // $this->layouts->view(config_item("cpanel").'content/profile/form',array(),$data);
  //MODAL EDIT
  $this->layouts->view(config_item("cpanel").'content/profile/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}


}
/* End Controller */
