<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Video.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Video.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-23 07:06:37 */
/* http://harviacode.com */

 class Video extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Video_model','model');
      if ($this->cl->acl("video")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('video', 'video', 'trim|xss_clean|required|max_length[150]');
		$this->form_validation->set_rules('desc', 'desc', 'trim|xss_clean|max_length[250]');
		$this->form_validation->set_rules('embed', 'embed', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Video');
    $this->layouts->view(config_item("cpanel").'content/video/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Video');
        $data=array('layout_title' => 'Video',
										'id_video' => $row->id_video,
										'video' => $row->video,
										'desc' => $row->desc,
										'embed' => $row->embed,
									);
				 $this->layouts->view(config_item("cpanel").'content/video/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/video/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'video' => $this->input->post('video',TRUE),
																'desc' => $this->input->post('desc',TRUE),
																'embed' => $this->input->post('embed',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Video');
      $data = array('layout_title' => 'Video',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'video/tambah/aksi'),
											'id_video' => set_value('id_video'),
											'video' => set_value('video'),
											'desc' => set_value('desc'),
											'embed' => set_value('embed'),
											);
			 $this->layouts->view(config_item("cpanel").'content/video/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/video/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'video' => $this->input->post('video',TRUE),
																'desc' => $this->input->post('desc',TRUE),
																'embed' => $this->input->post('embed',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Video');
        $data = array('layout_title' => 'Video',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'video/edit/'.$id.'/aksi'),
											'id_video' => set_value('id_video', $row->id_video),
											'video' => set_value('video', $row->video),
											'desc' => set_value('desc', $row->desc),
											'embed' => set_value('embed', $row->embed),
											);
			 $this->layouts->view(config_item("cpanel").'content/video/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/video/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
