<?php

$string = "<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');";

$string .= "\n\n\n\n/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */
/* http://harviacode.com */";


$string .="\n\n class " . $m . " extends CI_Model{
  var \$table = '$table_name';
  var \$id    = '$pk';";


  if ($jenis_tabel <> 'reguler_table') {

  $column_all = array();
  foreach ($all as $row) {
      $column_all[] = $row['column_name'];
  }
  $columnall = implode(',', $column_all);

  $string .="\n\n    // datatables
      function json() {
          \$this->datatables->select('".$columnall."');
          \$this->datatables->from('".$table_name."');
          //add this line for join
          //\$this->datatables->join('table2', '".$table_name.".field = table2.field');
          \$this->datatables->add_column('action',
          '<a href=\"'.site_url(\"$direct_url$c_url/detail/$1\").'\" id=\"detail\" class=\"btn btn-sm btn-primary\">detail</a>
           <a href=\"'.site_url(\"$direct_url$c_url/edit/$1\").'\" id=\"edit\" class=\"btn btn-sm btn-warning\">edit</a>
           <a href=\"'.site_url(\"$direct_url$c_url/hapus/$1\").'\" id=\"hapus\" class=\"btn btn-sm btn-danger\">hapus</a>',
           '$pk');
          return \$this->datatables->generate();
      }";
  }

$string .="\n\n
     function get_data()
      {
        return \$this->db->query(\"SELECT * FROM \$this->table ORDER BY \$this->id DESC\");
      }";

$string .="\n\n
      function get_insert(\$data)
        {
          return \$this->db->insert(\$this->table,\$data);
        }";

$string .="\n\n
      function get_where(\$where)
        {
          return \$this->db->where(\$this->id,\$where)
                          ->get(\$this->table)
                          ->row();
        }";

$string .="\n\n
      function get_update(\$where,\$data)
        {
          return \$this->db
                ->where(\$this->id,\$where)
                ->update(\$this->table,\$data);
        }";

$string .="\n\n
      function get_delete(\$where)
        {
          return \$this->db->where(\$this->id,\$where)
                          ->delete(\$this->table);
        }";



  $string .="\n\n}
  /* End Model */
  ";

$hasil_model = createFile($string, $target."".$direct_created ."models/" . $m_file);

 ?>
