<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-21 21:54:35 */
/* http://harviacode.com */

 class Album_model extends CI_Model{
  var $table = 'album';
  var $id    = 'id_album';


  function json_image($id) {
      $this->datatables->select('id_galery_image,image');
      $this->datatables->from('galery_image');
      $this->datatables->where('id_album',$id);
      //add this line for join
      //$this->datatables->join('table2', 'agenda.field = table2.field');
      $this->datatables->add_column('action',
      '<a href="'.site_url(config_item("cpanel")."album/hapus_image/$1").'" id="hapus" class="btn btn-sm btn-danger">hapus</a>',
       'id_galery_image');
      return $this->datatables->generate();
  }

  function get_insert_image($table,$data)
    {
      return $this->db->insert($table,$data);
    }

    function get_where_image($where,$table)
      {
        return $this->db->where($where)
                        ->get($table);
      }

      function get_delete_image($where,$table)
        {
          return $this->db->where($where)
                          ->delete($table);
        }


        //end image

     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }

        function get_insert($data)
          {
            return $this->db->insert($this->table,$data);
          }



      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          return $this->db->where($this->id,$where)
                          ->delete($this->table);
        }

}
  /* End Model */
