<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-30 18:31:26 */
/* http://harviacode.com */

 class Litbang_model extends CI_Model{
  var $table = 'litbang';
  var $id    = 'id_litbang';

    // datatables
      function json() {
          $this->datatables->select('id_litbang,slug,judul,penyusun,deskripsi,file,created_at');
          $this->datatables->from('litbang');
          //add this line for join
          //$this->datatables->join('table2', 'litbang.field = table2.field');
          $this->datatables->add_column('action',
          '<a href="'.site_url("administrator/litbang/detail/$1").'" id="detail" class="btn btn-xs btn-primary"><i class="fa fa-file-text"></i> detail</a>&nbsp;
           <a href="'.site_url("administrator/litbang/edit/$1").'" id="edit" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> edit</a>&nbsp;
           <a href="'.site_url("administrator/litbang/hapus/$1").'" id="hapus" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i> hapus</a>',
           'id_litbang');
          return $this->datatables->generate();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          return $this->db->where($this->id,$where)
                          ->delete($this->table);
        }

}
  /* End Model */
